import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const dirs = ["src", "scripts"];
const exts = [".js", ".jsx", ".css"];
const skip = ["node_modules", "dist", ".git", "public"];

const files = [];
for (const d of dirs) {
  const walk = (dir) => {
    for (const e of readdirSync(dir)) {
      const p = join(dir, e);
      if (skip.some((s) => p.includes(s))) continue;
      const st = statSync(p);
      if (st.isDirectory()) walk(p);
      else if (exts.some((x) => e.endsWith(x)) && !e.endsWith(".map")) files.push(p);
    }
  };
  walk(join(root, d));
}
files.sort();

let out = `# Source Appendix (generated by \`npm run gendocs\`)\n\n`;
out += `> Full generated source for the IGNITE codebase. ${files.length} files.\n\n`;

let total = 0;
for (const f of files) {
  const content = readFileSync(f, "utf8");
  const rel = relative(root, f);
  const lines = content.split("\n");
  total += lines.length;
  out += `## \`${rel}\` — ${lines.length} lines\n\n\`\`\`\n${content}\n\`\`\`\n\n`;
}

writeFileSync(join(root, "docs", "08_SOURCE_APPENDIX.md"), out);
console.log(`Source appendix: ${files.length} files, ${total} lines → docs/08_SOURCE_APPENDIX.md`);
